## Numpy Array and Basics
learn about Numpy from YT

In [3]:
import numpy as np

### creating array from list

In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1d array is : ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2d array is : ", arr_2d)

1d array is :  [1 2 3 4 5]
2d array is :  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [17]:
# py_list = [1,2,3]
# print("Python list multiplication : ", py_list * 2)

# np_array = np.array([1,2,3]) #Element wise multiplication
# print("Python array multiplication : ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np.array = np.arange(1000000) * 2
print("\n numpy operation time: ", time.time() - start)


 List operation time:  0.1115560531616211

 numpy operation time:  0.0026984214782714844


### Creating Array from Scratch

In [13]:
zeros = np.zeros((3,4))
print("zeros matrix : \n", zeros)

ones = np.ones((2,3))
print("ones matrix : \n", ones);

full = np.full((2,2), 6)
print("full matrix : \n", full);

random = np.random.random((4,5))
print("random matrix : \n", random);

sequence = np.arange(0, 10)
print("sequence matrix : \n", sequence);

zeros matrix : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones matrix : 
 [[1. 1. 1.]
 [1. 1. 1.]]
full matrix : 
 [[6 6]
 [6 6]]
random matrix : 
 [[0.69354924 0.17783834 0.71665214 0.78489481 0.6093751 ]
 [0.91022358 0.05397482 0.88690906 0.06427551 0.44276002]
 [0.28872882 0.10496105 0.22203354 0.88305363 0.06573028]
 [0.20901069 0.45607461 0.45256844 0.70658807 0.40275712]]
sequence matrix : 
 [0 1 2 3 4 5 6 7 8 9]


### Vector, Matrix and Tensor 

In [15]:
vector = np.array([1,2,3]);
print("vector: ", vector);

matrix = np.array([[1,2,3],
                   [4,5,6],])

print("matrix: ", matrix);

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("tensor: ", tensor);

vector:  [1 2 3]
matrix:  [[1 2 3]
 [4 5 6]]
tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
