## Numpy Array and Basics
learn about Numpy from YT

In [3]:
import numpy as np

### creating array from list

In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1d array is : ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2d array is : ", arr_2d)

1d array is :  [1 2 3 4 5]
2d array is :  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [17]:
# py_list = [1,2,3]
# print("Python list multiplication : ", py_list * 2)

# np_array = np.array([1,2,3]) #Element wise multiplication
# print("Python array multiplication : ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np.array = np.arange(1000000) * 2
print("\n numpy operation time: ", time.time() - start)


 List operation time:  0.1115560531616211

 numpy operation time:  0.0026984214782714844


### Creating Array from Scratch

In [11]:
zeros = np.zeros((3,4))
print("zeros matrix : \n", zeros)

ones = np.ones((2,3))
print("ones matrix : \n", ones);

full = np.full((2,2), 6)
print("full matrix : \n", full);

random = np.random.random((4,5))
print("random matrix : \n", random);

zeros matrix : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones matrix : 
 [[1. 1. 1.]
 [1. 1. 1.]]
full matrix : 
 [[6 6]
 [6 6]]
random matrix : 
 [[0.88936719 0.14367171 0.96425749 0.4182011  0.13790087]
 [0.8041762  0.80693756 0.71430174 0.00550202 0.48554348]
 [0.9937496  0.89233515 0.64879531 0.18414684 0.73865802]
 [0.70177069 0.40895432 0.42537047 0.75391382 0.31665266]]
